### ISSUE TITLE
Flip image/source

### ISSUE THREAD

**Issue by jLynx** [niqdev/ipcam-view#42]
Is there currently a way to flip the image?

**Comment by niqdev** [comment]
The library supports rotation, is this what you mean?

**Comment by jLynx** [comment]
Can you give an example on how I would do this?

**Comment by jLynx** [comment]
![flipped](https://user-images.githubusercontent.com/4393979/28690551-b2309dce-736d-11e7-936e-f27380053d9a.png)
Here is an example

**Comment by niqdev** [comment]
Nope is not possible, sorry.
If you want, you are welcome and you can do a PR, I'll be happy to merge it

**Comment by jLynx** [comment]
Alright, I guess you could add this as a feature request and I will try get around to adding it in

**Comment by jLynx** [comment]
@niqdev I had some time right now and it was actually quite easy to do, so I have made a pull request now :D

**Comment by niqdev** [comment]
@jLynx fantastic!
I'll merge it now but I will release the lib this weekend, did you test it? any regression?

**Comment by jLynx** [comment]
I did test it and had no problems with it at all. I guess we can close this now since it has been implemented

**Comment by niqdev** [comment]
i'll keep it open until I'll add a comment with the new lib version and when I'll release the demo on the store.
Thanks

**Comment by niqdev** [comment]
I've released version `1.2.0`, you are welcome to add a link of your app in the readme.
Thanks

**Comment by emrekilic** [comment]
hello @niqdev. 
My source mjpeg video comes in 90 degrees inverted. The flip feature does not fix it. What do I have to do to rotate the image 90 degrees?

**Comment by niqdev** [comment]
Hi @emrekilic, I apologize for the late response.

Could you please provide more information (code snippets / stacktrace) about your issue?

Thanks
